#!/bin/sh
# postinst script for phpmyadmin

set -e

if [ -n "$UPGRADE" ]; then
	exit 0
fi

addgroup --system inputmangler
cd /etc/udev/rules.d/
/usr/share/inputmangler/make_udev_rules.sh inputmangler > /dev/null

echo inputdummy > /etc/modules-load.d/inputmangler.conf

echo inputmangler installed!
echo to use it, you must do the following:
echo edit /etc/udev/rules.d/45-inputmangler.rules and uncomment the lines describing the devices you wish inputmangler to use
echo add the users that should be able to use inputmangler to its group with 
echo $ adduser username inputmangler
echo as user run /usr/share/inputmangler/setupHelper.sh to create a default configuration 

exit 0
